### PR TITLE
Return local time instead of UTC time from Controller

### PR DESCRIPTION
**Pull request by proddy**

### CODE REVIEW

**Comment by proddy** [comment]
Right, the unit test failed but don't understand why as it seems to be comparing two ints. Need some help here!

**Comment by MartinHjelmare** [comment]
We're mocking the imported time module, in the existing test, but only set a mocked return value for `time.time`. After your changes we no longer use `time.time` but `time.localtime`, and `calendar.timegm`. I would try to set the return value for `time.localtime` to a time tuple that I know will be converted to something specific after using `calendar.timegm`. You could also patch the latter directly.

**Comment by MartinHjelmare** [comment]
@proddy Sorry if I was too unspecific in my answer above. Let me know if I should make a more detailed instruction, so you can fix the test, or if you want me to do that. I should be able to add a commit to this branch, and you will still be counted as a contributor since you made the initial commit of the PR.

**Comment by proddy** [comment]
@MartinHjelmare I'm actually new to python. I did spend some time reading up on mock'ing in python but it's all too confusing and will probably take me hours an many nights to get right. So very happy for you to make the change. Thanks.

**Comment by MartinHjelmare** [comment]
I've fixed the test. Thanks for the PR! Merging.

**Comment by proddy** [comment]
thanks @MartinHjelmare . I would have never been able to work that out myself (i..e. using time.gmtime). I learned some more python and mock patch today.

**Pull request merged**
