### PR TITLE
Handle unexpected exeptions while decoding

### PR DESCRIPTION
**Pull request by oeysteinhansen**
This does not solve the theolind/pymysensors#10 issue but helps the thread continue if this or equal issues happens.

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
Hi!

I think this is the wrong approach. If an error can't be avoided through a fix, the error should be caught specifically and as close to the origin as possible. Adding this except statement in the run method will catch all upstream errors unspecifically. I'm working on trying to move some except statements away from run and closer to where the possible errors would emerge. I think we should try to follow that line of thought.

This https://github.com/theolind/pymysensors/pull/38 should fix the error during presentation.

Do you have an example log from the error you've experienced? If so it would be good to add that to #10. If you have another error you should report it in a new issue. Then we can try to fix it or handle it from there.

**Comment by oeysteinhansen** [comment]
This is the exeption I encountered during startup of pymysensors / homeassistant.

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/pi/.homeassistant/lib/mysensors/mysensors.py", line 328, in run
    response = self.handle_queue()
  File "/home/pi/.homeassistant/lib/mysensors/mysensors.py", line 233, in handle_queue
    reply = func(*args, **kwargs)
  File "/home/pi/.homeassistant/lib/mysensors/mysensors.py", line 115, in logic
    self._handle_presentation(msg)
  File "/home/pi/.homeassistant/lib/mysensors/mysensors.py", line 49, in _handle_presentation
    self.sensors[msg.node_id].add_child_sensor(msg.child_id,
KeyError: 0
```

**Comment by oeysteinhansen** [comment]
> I'm also working on adding the feature for requesting a new presentation that's available in mysensors dev branch (2.0).

In my setup every mysensor node resends presentation every hour. So network becomes self healing. This is to catch if I change / reset Controller, or node is out of wireless reach when powering up.

**Comment by MartinHjelmare** [comment]
Which lines of code or serial messages for presentation do you resend?

**Comment by oeysteinhansen** [comment]
Her is my sendMySensorsPresentation function that is called at startup and then after every hour.

```
void sendMySensorsPresentation(){
  // Send the sketch version information to the gateway and Controller
  gw.sendSketchInfo("SolarMonitor", "1.0");

  // Register analog sensors
  gw.present(CHILD_SENSOR_ID_A0, S_MULTIMETER, "Solar voltage");
  gw.present(CHILD_SENSOR_ID_A3, S_MULTIMETER, "Solar current");
  gw.present(CHILD_SENSOR_ID_CHIP_TEMP, S_TEMP, "Chip Temp");

  // Register this device as power sensor
  gw.present(CHILD_SENSOR_ID_SOLAR_POWER, S_POWER, "Solar power");

  // Register all relays as light switches
  gw.present(CHILD_SENSOR_ID_RELAY_1, S_LIGHT);
  gw.present(CHILD_SENSOR_ID_RELAY_2, S_LIGHT);
}
```

I do not know if this is how it should be done, but i thought it to be smart.

**Comment by MartinHjelmare** [comment]
I think you idea to resend the presentation messages is very good!

Have you tried to also resend the node presentation? I.e.
```
gw.begin();
```
I haven't tried to do that myself, but If that doesn't produce any errors on the arduino side, I think that would solve any problems after #38 is merged.

If the node is already added to pymysensors/homeassistant when it is re-presented, the new presentation will just be ignored. If the node is not already added, it will be added when re-presented. Then the sensors, that are re-presented and not already added, are able to also be added.

**Comment by oeysteinhansen** [comment]
As I can see, the `gw.begin();` command does a hole lot of stuff, Hardware init, and setting node Id. So i dont think it is a god ide to call that after startup.

**Comment by MartinHjelmare** [comment]
I looked into the source for mysensors and saw that it uses the same method to present nodes as for child sensors. You can present the node if you use 255 for child_id and sensor_type should be 17 for regular node or 18 for repeater node.
```
gw.present(255, 17);
```

**Comment by MartinHjelmare** [comment]
I'm closing this in favor of #38.

**Pull request closed without merging**
