### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by Br3nda**

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
Since your other PR is merged now, you should rebase this one off dev branch. Please also sqaush your commits into one. Sorry for the runaround.

**Comment by Br3nda** [comment]
Squashed to one commit

**Comment by MartinHjelmare** [comment]
:+1: 
I'd like to merge this. But even better would be to also activate travis for this repo. What do you say, @theolind ?

**Comment by theolind** [comment]
I think this is great and have enabled travis for the repository. However, I think "travis.yml" needs to be renamed to ".travis.yml" for travis to pick it up and use it.

**Comment by MartinHjelmare** [comment]
@theolind Great! Regarding the name, yeah it has to be named like that, and I think it is, it's just the commit message that reads a bit different.

I'm merging this now.

**Comment by MartinHjelmare** [comment]
[Build Status](https://travis-ci.org/theolind/pymysensors)

**Pull request merged**
