### PR TITLE
Add new internal sub-types

### PR DESCRIPTION
**Pull request by jslove**
Add new internal sub-types added in 2.2

### CODE REVIEW

**Comment by jslove** [comment]
I added the validations based on the types I found in the cpp code.

**Comment by MartinHjelmare** [comment]
I adjusted the validation of the payload so it returns a string in the end. I also extended the tests to cover the new types.

**Comment by MartinHjelmare** [comment]
Thanks! :tada:

**Comment by jslove** [comment]
Thanks, I was winging it on the validation.

**Pull request merged**
